FROM node:22-alpine

WORKDIR /app

# Dependencies installieren
COPY package*.json ./
RUN npm install

EXPOSE 3000

# Vite Dev-Server starten (Hot-Reload)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
